### ISSUE TITLE
What is the endpoint?

### ISSUE THREAD

**Issue by ZedZipDev** [rahulrai-in/movie-reviews#2]
Great sample, thank you.
One question.
I have NET.Core client app, try to connect and work with the service.
The client cannot connect. What is the GraphQL endpoint URL of the service?
I use TheGraphClient Nuget.
My code:

```
var client = new TheGraphClient("http://localhost:5000/graphql");
            string query = @"{
                            movie(id: ""72d95bfd-1dac-4bc2-adc1-f28fd43777fd"") {
                            id
                            name
                            reviews {
                                        reviewer
                                        stars
                            }
                          }
                         }";

            GraphQL.GraphQLResponse<Movie> result2 = null; ;
            try
            {
                result2 = await client.SendQueryAsync<Movie>(query);
            }
            catch(Exception xxx)
            {
                Console.WriteLine("{0}", xxx);
            }
```

I receive an exception: 
xxx = {"The HTTP request failed with status code NotFound"}

**Comment by rahulrai-in** [comment]
Are you able to access the playground and test the query at the URL that you mentioned?

**Comment by ZedZipDev** [comment]
Yes, I run my browser http://localhost:5000 and can work with Altair, i.e. it uses the http://localhost:5000/graphql to post test queries.
I have attached my test console app here.

[GQLConsole.zip](https://github.com/rahulrai-in/movie-reviews/files/6643856/GQLConsole.zip)

**Comment by ZedZipDev** [comment]
Hi Rahul, can you help me how to fix it?
Thanks.

**Comment by rahulrai-in** [comment]
Hey mate, I haven't used the library that you used in the sample. I tried building a simple client using [GraphQL Client](https://github.com/graphql-dotnet/graphql-client) as follows and it works:

```
            var graphQLClient = new GraphQLHttpClient("https://localhost:5001/graphql", new NewtonsoftJsonSerializer());
            var q = new GraphQLRequest
            {
                Query = @"
                    query {
                      movie(id: ""72d95bfd-1dac-4bc2-adc1-f28fd43777fd"") {
                        id
                        name
                        reviews {
                          reviewer
                          stars
                        }
                      }
                    }"
            };

            var graphQLResponse = await graphQLClient.SendQueryAsync<dynamic>(q);
```

Here is a screenshot of the response. Of course, replace `dynamic` with whatever response type you are expecting from the response.
![image](https://user-images.githubusercontent.com/11886524/121993536-f914e380-cde6-11eb-8f0f-f63b9df049c8.png)

**Comment by ZedZipDev** [comment]
Thank you very much, it seems it was my mistake to use that Nuget.
