### ISSUE TITLE
How to use Subscribe queries?

### ISSUE THREAD

**Issue by ZedZipDev** [rahulrai-in/movie-reviews#4]
Is it possible to use Subscribe queries? Especially interesting: how to implement them on the server side and consume them in the NET Core client?

**Comment by rahulrai-in** [comment]
Sorry mate. This is beyond the scope of the blog post.

**Comment by ZedZipDev** [comment]
ok, thanx, it will be great. 
Are you going to create the blog post about how to use subscriptions in c# graphql client and server?
